import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Abdul Irfan",
  description: "Generated by createclear next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} no-scrollbar `}
        style={{ fontFamily: `"Dennis Sans", sans-serif` }}
      >
        <div className="w-[100vw] overflow-x-hidden ">{children}</div>
      </body>
    </html>
  );
}
